### ISSUE TITLE
Temperature wrong value

### ISSUE THREAD

**Issue by OmarAlkassab** [tinkeringtech/HDC2010_breakout#1]
First, many thanks for this great libarary.

I'm using the STM32L151CBT6 using platformio, and when I run the example code, the following result appears on the serial monitor:

Temperature (C): -40.00..Humidity (%): 51.61
Temperature (C): -40.00..Humidity (%): 51.61
Temperature (C): -40.00..Humidity (%): 51.57
Temperature (C): -40.00..Humidity (%): 51.61
Temperature (C): -39.96..Humidity (%): 51.76
Temperature (C): -39.96..Humidity (%): 51.76
Temperature (C): -39.96..Humidity (%): 51.91

What could be the problem?

**Comment by tinkeringtech** [comment]
Hi there! Did you test on an Arduino?
Also, did you ensure the soldering to the header on the sensor is ok? Please also check the wiring.
